# Key Vault + secrets + access. Secrets are ingested from secret.tfvars (sensitive
# vars) and from resource outputs (connection strings), then referenced by the
# Node app via @Microsoft.KeyVault(...) app settings.

resource "azurerm_key_vault" "this" {
  name                       = local.kv_name
  resource_group_name        = azurerm_resource_group.this.name
  location                   = azurerm_resource_group.this.location
  tenant_id                  = data.azurerm_client_config.current.tenant_id
  sku_name                   = "standard"
  soft_delete_retention_days = 7
  purge_protection_enabled   = false # prod: set true (blocks accidental hard-delete)
  rbac_authorization_enabled = false # using access policies (immediate, no RBAC propagation wait)
  tags                       = local.tags
}

# The principal running Terraform must be able to write secrets.
resource "azurerm_key_vault_access_policy" "deployer" {
  key_vault_id = azurerm_key_vault.this.id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = data.azurerm_client_config.current.object_id

  secret_permissions = ["Get", "List", "Set", "Delete", "Purge", "Recover"]
}

# The Node Function App's managed identity may read secrets (Key Vault references).
resource "azurerm_key_vault_access_policy" "node_app" {
  key_vault_id = azurerm_key_vault.this.id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = module.node_app.principal_id

  secret_permissions = ["Get", "List"]
}

locals {
  # Candidate secrets. Non-Azure keys come from secret.tfvars; every Azure key is
  # generated by the resources in this RG and pushed into Key Vault.
  secret_values = {
    # non-Azure (from secret.tfvars)
    "youtube-api-key"           = var.youtube_api_key
    "gemini-api-key"            = var.gemini_api_key
    "pubsubhubbub-verify-token" = var.pubsubhubbub_verify_token
    # Azure-generated (from the resources in this RG)
    "cosmos-connection-string"   = azurerm_cosmosdb_account.this.primary_sql_connection_string
    "eventhub-connection-string" = azurerm_eventhub_namespace_authorization_rule.app.primary_connection_string
    "storage-connection-string"  = azurerm_storage_account.this.primary_connection_string
    "vision-key"                 = azurerm_cognitive_account.vision.primary_access_key
    "language-key"               = azurerm_cognitive_account.language.primary_access_key
  }

  # All secrets are required and always created. Keys are a static list (known at
  # plan time — for_each can't take keys derived from apply-time resource outputs).
  secret_keys = toset([
    "youtube-api-key",
    "gemini-api-key",
    "pubsubhubbub-verify-token",
    "cosmos-connection-string",
    "eventhub-connection-string",
    "storage-connection-string",
    "vision-key",
    "language-key",
  ])

  # env-var value => Key Vault reference (latest version).
  kv_ref = merge(
    { for k, s in azurerm_key_vault_secret.app : k => "@Microsoft.KeyVault(SecretUri=${s.versionless_id})" },
    { "transcript-function-key" = "@Microsoft.KeyVault(SecretUri=${azurerm_key_vault_secret.transcript_function_key.versionless_id})" },
  )
}

resource "azurerm_key_vault_secret" "app" {
  for_each     = local.secret_keys
  name         = each.key
  value        = local.secret_values[each.key]
  key_vault_id = azurerm_key_vault.this.id
  tags         = local.tags

  depends_on = [azurerm_key_vault_access_policy.deployer]
}

# The Python app's function key is unknown until its code is deployed, so we seed
# a placeholder and let deploy.sh write the real value (ignore_changes keeps a
# later `terraform apply` from reverting it).
resource "azurerm_key_vault_secret" "transcript_function_key" {
  name         = "transcript-function-key"
  value        = "set-by-deploy-script"
  key_vault_id = azurerm_key_vault.this.id
  tags         = local.tags

  depends_on = [azurerm_key_vault_access_policy.deployer]

  lifecycle {
    ignore_changes = [value]
  }
}
