# ─────────────────────────────────────────────────────────────────────────────
# PUBLIC configuration (safe to commit) — supply via terraform.tfvars.
# The 3 non-Azure secrets are declared here but marked `sensitive` and MUST come
# from the git-ignored secret.tfvars. Every Azure key (Cosmos, Event Hub,
# Storage, Vision, Language) is GENERATED by Terraform and pushed into Key Vault.
# ─────────────────────────────────────────────────────────────────────────────

variable "subscription_id" {
  type        = string
  description = "Azure subscription ID to deploy into."
}

variable "location" {
  type        = string
  description = "Azure region for most resources."
  default     = "centralindia"
}

variable "cosmos_location" {
  type        = string
  description = "Cosmos DB region. Kept in the US (West US 2) — the Students subscription can't provision it in Central India (matches the old setup)."
  default     = "westus2"
}

variable "ai_services_location" {
  type        = string
  description = "Region for the two Cognitive accounts (Vision = ComputerVision, Language = TextAnalytics). Central India works; use a region with Image Analysis 4.0 (e.g. eastus) if it doesn't."
  default     = "centralindia"
}

variable "static_web_app_location" {
  type        = string
  description = "Static Web Apps is only available in a subset of regions (not centralindia). Closest to India is East Asia."
  default     = "eastasia"
}

variable "resource_group_name" {
  type        = string
  description = "Single resource group for all infra (shared by prod + local dev)."
  default     = "BaitRadar"
}

variable "name_prefix" {
  type        = string
  description = "Lowercase prefix for all resource names (many Azure names disallow uppercase)."
  default     = "baitradar"
}

variable "environment" {
  type        = string
  description = "Environment label used for tagging only (naming is not per-env — one shared RG)."
  default     = "shared"
}

variable "extra_tags" {
  type        = map(string)
  description = "Additional tags merged onto every resource."
  default     = {}
}

# ── Non-secret application configuration (maps to src/config/env.ts defaults) ──

variable "cosmos_database" {
  type        = string
  description = "Cosmos SQL database name."
  default     = "ytanalytics"
}

variable "ingestion_queue_name" {
  type        = string
  description = "Storage Queue for the video (content) stage — metadata / transcript / packaging."
  default     = "video-ingestion-queue"
}

variable "comment_queue_name" {
  type        = string
  description = "Storage Queue for the comment stage — top-100 comments + sentiment + betrayal."
  default     = "comment-processing-queue"
}

variable "min_video_seconds_threshold" {
  type        = number
  description = "Videos shorter than this (seconds) are treated as Shorts and skipped."
  default     = 60
}

variable "pubsubhubbub_hub_url" {
  type        = string
  description = "WebSub hub subscribe endpoint."
  default     = "https://pubsubhubbub.appspot.com/subscribe"
}

variable "pubsubhubbub_lease_seconds" {
  type        = number
  description = "WebSub subscription lease seconds."
  default     = 432000
}

# ── AI service SKU (provisioned fresh in this RG) ────────────────────────────
# Standard tier by default: Azure allows only ONE free (F0) account of each kind
# per subscription, which collides with the old RG during migration.
variable "language_sku" {
  type        = string
  description = "Azure AI Language (TextAnalytics) SKU. F0 (free, one per sub) or S."
  default     = "S"
}

variable "apim_publisher_name" {
  type        = string
  description = "APIM publisher (org) name."
  default     = "BaitRadar"
}

variable "apim_publisher_email" {
  type        = string
  description = "APIM publisher email (required by APIM)."
  default     = "kishujaiswal3@gmail.com"
}

# ─────────────────────────────────────────────────────────────────────────────
# SENSITIVE — the only keys Azure can't generate. Supply ONLY via secret.tfvars.
# Terraform writes them into Key Vault; the apps read them via Key Vault refs.
# ─────────────────────────────────────────────────────────────────────────────

variable "youtube_api_key" {
  type        = string
  description = "YouTube Data API v3 key."
  sensitive   = true
}

variable "gemini_api_key" {
  type        = string
  description = "Google Gemini API key."
  sensitive   = true
}

variable "pubsubhubbub_verify_token" {
  type        = string
  description = "Shared secret echoed during WebSub verification."
  sensitive   = true
}
